FROM nvcr.io/nvidia/deepstream:6.1-triton
ADD . /opt/nvidia/meikuang
RUN echo "change ubuntu mirror!" &&\
mkdir -p /workspace/triton_deploy/models &&\
mkdir -p /workspace/triton_deploy/plugins &&\ 
mkdir -p /home/ky &&\
cp /opt/nvidia/meikuang/sources.list /etc/apt/sources.list && apt update &&\
apt install -y libspdlog-dev &&\
apt install -y openssh-server &&\
cp -r /opt/nvidia/meikuang/models /workspace/triton_deploy/ &&\
cp /opt/nvidia/meikuang/sshd_config /etc/ssh/ &&\
cp /opt/nvidia/meikuang/libmyplugins.so /workspace/triton_deploy/plugins/ &&\
chmod 777 /opt/nvidia/meikuang/autostart.sh
RUN echo "root:123456" | chpasswd

ENTRYPOINT ["sh" ,"/opt/nvidia/meikuang/autostart.sh"]

